### ISSUE TITLE
Splits not loading

### ISSUE THREAD

**Issue by Hazard-The-AD** [DxtrPog/IndigoParkAutoSplitter#1]
The splits for some reason do not want to load up for me. I'm following all the instructions provided but still running into the error of the splits not being recognised. Maybe I am doing something wrong here? I'm not too sure.

![image](https://github.com/DxtrPog/IndigoParkAutoSplitter/assets/20299632/787831e1-7117-4c18-9503-1acccc309da4)
![image](https://github.com/DxtrPog/IndigoParkAutoSplitter/assets/20299632/ca7118c9-2e72-46b5-91dd-57b4088167e9)
![image](https://github.com/DxtrPog/IndigoParkAutoSplitter/assets/20299632/896cabc1-8b69-40dc-904d-6de9f606fab1)

**Comment by kiwiicore** [comment]
You need to add the splits yourself. You need a total of 10 splits as it splits at every loading zone.
